<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Switches the semantic-search columns from jsonb to real pgvector so cosine
 * similarity runs in PostgreSQL (operator `<=>`) instead of in PHP.
 *
 * Embedding dimension = 3072 (Gemini). No ANN index is created (pgvector indexes
 * cap at 2000 dims and the dataset is tiny) — exact sequential scan is used.
 * Existing vectors are dropped and regenerated by the seeders / knowledge:index.
 */
return new class extends Migration
{
    /** @var array<int, string> */
    private array $tables = ['knowledge_chunks', 'claim_verifications', 'disaster_events'];

    public function up(): void
    {
        DB::statement('CREATE EXTENSION IF NOT EXISTS vector');

        foreach ($this->tables as $table) {
            DB::statement("ALTER TABLE {$table} DROP COLUMN IF EXISTS embedding");
            DB::statement("ALTER TABLE {$table} ADD COLUMN embedding vector(3072)");
        }
    }

    public function down(): void
    {
        foreach ($this->tables as $table) {
            DB::statement("ALTER TABLE {$table} DROP COLUMN IF EXISTS embedding");
            DB::statement("ALTER TABLE {$table} ADD COLUMN embedding jsonb");
        }
    }
};
